spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?serverTimezone=UTC
    username: root
    password: hao20001010


mybatis:
  mapper-locations: mapper/**
  type-aliases-package: com.jwt.entity

server:
  port: 8081

